/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class winsyslib_WinSysLib */

#ifndef _Included_winsyslib_WinSysLib
#define _Included_winsyslib_WinSysLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     winsyslib_WinSysLib
 * Method:    getNumProcessors
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_winsyslib_WinSysLib_getNumProcessors
  (JNIEnv *, jobject);

/*
 * Class:     winsyslib_WinSysLib
 * Method:    setProcessProcessorAffinity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_winsyslib_WinSysLib_setProcessProcessorAffinity
  (JNIEnv *, jobject, jint);

/*
 * Class:     winsyslib_WinSysLib
 * Method:    setThreadProcessorAffinity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_winsyslib_WinSysLib_setThreadProcessorAffinity
  (JNIEnv *, jobject, jint);

/*
 * Class:     winsyslib_WinSysLib
 * Method:    setNumProcessorAffinityForProcess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_winsyslib_WinSysLib_setNumProcessorAffinityForProcess
  (JNIEnv *, jobject, jint);

/*
 * Class:     winsyslib_WinSysLib
 * Method:    setProcessorsToUseForProcess
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_winsyslib_WinSysLib_setProcessorsToUseForProcess___3II
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     winsyslib_WinSysLib
 * Method:    setThreadPriority
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_winsyslib_WinSysLib_setThreadPriority
  (JNIEnv *, jobject, jint);

/*
 * Class:     winsyslib_WinSysLib
 * Method:    getWindowHwnd
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_winsyslib_WinSysLib_getWindowHwnd
  (JNIEnv *, jobject, jstring);

/*
 * Class:     winsyslib_WinSysLib
 * Method:    setProcessorsToUseForProcess
 * Signature: (Ljava/lang/String;[II)V
 */
JNIEXPORT void JNICALL Java_winsyslib_WinSysLib_setProcessorsToUseForProcess__Ljava_lang_String_2_3II
  (JNIEnv *, jobject, jstring, jintArray, jint);

/*
 * Class:     winsyslib_WinSysLib
 * Method:    isWindowAlive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_winsyslib_WinSysLib_isWindowAlive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     winsyslib_WinSysLib
 * Method:    getProcessorSpeed
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_winsyslib_WinSysLib_getProcessorSpeed
  (JNIEnv *, jobject);

/*
 * Class:     winsyslib_WinSysLib
 * Method:    getProcessorName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_winsyslib_WinSysLib_getProcessorName
  (JNIEnv *, jobject);

/*
 * Class:     winsyslib_WinSysLib
 * Method:    getProcessorIdentifier
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_winsyslib_WinSysLib_getProcessorIdentifier
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
